udp_topics:
- name: "/xbotcore/joint_states"
  compress: true 
  rate: 10.0
   
- name: "/xbotcore/statistics"
  compress: true 
  rate: 5.0
  
- name: "/tf_throttle/tf"
  compress: true

#tcp_topics:
