udp_topics:
- name: "/xbotcore/joint_states"
  compress: true 
  rate: 10.0
   
- name: "/xbotcore/statistics"
  compress: true 
  rate: 5.0
  
- name: "/tf_throttle/tf"
  compress: true
  
- name: "/tf_static"
  compress: true  
  rate: 100.0
  
- name: "/cartesian/pelvis/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/com/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/arm1_8/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/arm2_8/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/wheel_1/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/wheel_2/state"
  compress: true  
  rate: 10.0
  
- name: "/cartesian/wheel_3/state"
  compress: true  
  rate: 10.0  

- name: "/cartesian/wheel_4/state"
  compress: true  
  rate: 10.0    

#tcp_topics:
