image: ros:kinetic-ros-core

variables:
  ROS_PACKAGES_TO_INSTALL: ""
  USE_ROSDEP: "true"

before_script:
 - git clone https://git.ais.uni-bonn.de/nimbroshared/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash

catkin_build:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color

catkin_tools_tests:
  stage: test
  script:
    - ROS_TEST_RESULTS_DIR=$(pwd)/test_results catkin run_tests --no-status --force-color
  artifacts:
    paths:
      - test_results/
