image: ros:kinetic-robot

variables:
  ROS_PACKAGES_TO_INSTALL: ""
  USE_ROSDEP: "true"

before_script:
 - git clone https://git.ais.uni-bonn.de/nimbroshared/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash

catkin_build:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color

catkin_tools_tests:
  stage: test
  script:
    - . devel/setup.bash
    - ROS_TEST_RESULTS_DIR=$(pwd)/test_results catkin run_tests --no-status --force-color
    - find build -name test_results -type d -exec cp -R '{}' $CI_PROJECT_DIR/ ';' -print
    - cd $CI_PROJECT_DIR
    - python ros_gitlab_ci/summarize_results.py test_results/*/*.xml test_results/summary.xml
  artifacts:
    paths:
      - test_results/
