udp_topics:

- name: "/xbotcore/command"
  compress: true 
  rate: 100.0
  
- name: "/cartesian/pelvis/velocity_reference"
  compress: true 
  rate: 30.0
   
- name: "/cartesian/arm1_8/velocity_reference"
  compress: true 
  rate: 30.0
   
- name: "/cartesian/arm2_8/velocity_reference"
  compress: true 
  rate: 30.0

#tcp_topics:
